/**
 * The seam between a revision and the text it rewrites.
 *
 * `advisor-revision.test.ts` drives this through the service against a real
 * database, which is where the interesting rules live. These are the unit
 * questions that file cannot ask cheaply: what happens for a target that has
 * no such field, for one that has gone, and — the one worth having — whether
 * writing one field leaves the rest of the record exactly as it was. The last
 * is checked here against a *recording* double rather than a store, so what is
 * asserted is the call the service makes rather than the row that survives it:
 * a write that rebuilds a record from three fields and a write that preserves
 * eight produce the same row when the other five happen to be at their
 * defaults, which is the reading under which the `.partial()` trap hid.
 */

import type { AgentDefinitionRecord, SkillDefinition, Workspace } from '@metaclaude/shared';
import { REVISABLE_FIELDS, RevisionTargetKind } from '@metaclaude/shared';
import { describe, expect, it, vi } from 'vitest';
import {
  fieldSchema,
  fitsField,
  hasField,
  readRevisable,
  RevisionTargetError,
  sameText,
  textFingerprint,
  writeRevisable,
  type RevisionSurfaceDeps,
} from './revision.js';

const skill = (over: Partial<SkillDefinition> = {}): SkillDefinition =>
  ({
    id: 'skl_1',
    workspaceId: 'ws_1',
    name: 'review-migrations',
    description: 'Reviews migrations.',
    body: '# Review',
    category: 'engineering',
    enabled: false,
    isGlobal: true,
    workspaceIds: [],
    autoGenerated: false,
    useCount: 7,
    createdAt: 1,
    updatedAt: 1,
    ...over,
  }) as SkillDefinition;

const agent = (over: Partial<AgentDefinitionRecord> = {}): AgentDefinitionRecord =>
  ({
    id: 'agt_1',
    workspaceId: 'ws_1',
    name: 'reviewer',
    description: 'Reviews things.',
    prompt: 'Review.',
    category: 'engineering',
    tools: ['Read', 'Grep'],
    model: 'haiku',
    enabled: false,
    isGlobal: false,
    workspaceIds: ['ws_2'],
    createdAt: 1,
    updatedAt: 1,
    ...over,
  }) as AgentDefinitionRecord;

const workspace = (): Workspace =>
  ({
    id: 'ws_1',
    name: 'Alpha',
    slug: 'alpha',
    description: '',
    path: '/tmp/a',
    color: '#000000',
    icon: 'folder',
    archived: false,
    settings: { systemPromptAppend: 'Answer in French.' },
    createdAt: 1,
    updatedAt: 1,
  }) as Workspace;

/** Every dependency a recorder, so what is asserted is the call. */
function surface(over: Partial<RevisionSurfaceDeps> = {}) {
  const upsertSkill = vi.fn((input: unknown) => input as never);
  const upsertAgent = vi.fn((input: unknown) => input as never);
  const updateWorkspace = vi.fn(() => workspace() as never);
  const updateAutomation = vi.fn(() => ({}) as never);
  const deps: RevisionSurfaceDeps = {
    workspaces: { get: vi.fn(() => workspace()), update: updateWorkspace } as never,
    registry: {
      getSkill: vi.fn(() => skill()),
      upsertSkill,
      getAgent: vi.fn(() => agent()),
      upsertAgent,
    } as never,
    automations: {
      get: vi.fn(() => ({ id: 'aut_1', name: 'Morning', prompt: 'Review the day.' })),
      update: updateAutomation,
    } as never,
    ...over,
  };
  return { deps, upsertSkill, upsertAgent, updateWorkspace, updateAutomation };
}

describe('hasField', () => {
  it('knows which text each kind of target has', () => {
    expect(hasField('workspace', 'systemPromptAppend')).toBe(true);
    expect(hasField('workspace', 'body')).toBe(false);
    expect(hasField('skill', 'body')).toBe(true);
    expect(hasField('skill', 'prompt')).toBe(false);
    expect(hasField('agent', 'prompt')).toBe(true);
    expect(hasField('automation', 'prompt')).toBe(true);
    expect(hasField('automation', 'description')).toBe(false);
  });
});

describe('textFingerprint', () => {
  it('is stable for one text and different for another', () => {
    expect(textFingerprint('a')).toBe(textFingerprint('a'));
    expect(textFingerprint('a')).not.toBe(textFingerprint('b'));
  });

  /** Short enough to store and read, long enough not to collide in practice. */
  it('is sixteen hex characters, like the consolidation fingerprint beside it', () => {
    expect(textFingerprint('anything')).toMatch(/^[0-9a-f]{16}$/);
  });

  it('notices a change of one character, including whitespace', () => {
    expect(textFingerprint('a b')).not.toBe(textFingerprint('a  b'));
  });
});

describe('sameText', () => {
  it('is true for the same text', () => {
    expect(sameText('one\ntwo', 'one\ntwo')).toBe(true);
  });

  /**
   * A model asked to rewrite a prompt hands back the prompt with a newline on
   * the end often enough to matter, and a card whose diff is one invisible
   * character is one an operator cannot act on either way.
   */
  it('ignores trailing whitespace, which is what a model adds by accident', () => {
    expect(sameText('one', 'one\n')).toBe(true);
    expect(sameText('one', 'one   ')).toBe(true);
    expect(sameText('one\ntwo  ', 'one\ntwo')).toBe(true);
    expect(sameText('one\r\ntwo', 'one\ntwo')).toBe(true);
  });

  it('does not ignore a change anyone would see', () => {
    expect(sameText('one', 'one two')).toBe(false);
    expect(sameText('one', ' one')).toBe(false);
    expect(sameText('one\ntwo', 'one\n\ntwo')).toBe(false);
  });
});

describe('readRevisable', () => {
  it('reads each target’s text and its name', () => {
    const { deps } = surface();

    expect(readRevisable(deps, { kind: 'workspace', id: 'ws_1' }, 'systemPromptAppend')).toEqual({
      text: 'Answer in French.',
      name: 'Alpha',
      // A workspace's own instructions reach that workspace and no other, so
      // there is nothing here the card should warn about.
      global: false,
    });
    expect(readRevisable(deps, { kind: 'skill', id: 'skl_1' }, 'description')?.text).toBe('Reviews migrations.');
    expect(readRevisable(deps, { kind: 'skill', id: 'skl_1' }, 'body')?.text).toBe('# Review');
    expect(readRevisable(deps, { kind: 'agent', id: 'agt_1' }, 'prompt')?.text).toBe('Review.');
    expect(readRevisable(deps, { kind: 'agent', id: 'agt_1' }, 'description')?.text).toBe('Reviews things.');
    expect(readRevisable(deps, { kind: 'automation', id: 'aut_1' }, 'prompt')?.text).toBe('Review the day.');
  });

  /**
   * The reach, read from the record.
   *
   * It is what draws the card's warning that a rewrite reaches every workspace
   * rather than this one, and it was taken from the caller — which passed a
   * constant null, so the warning was on for every skill revision ever
   * proposed. Read from `isGlobal` and not from `workspaceId`: the latter
   * records who created the row, and an operator may widen the reach later
   * without it being rewritten.
   */
  it('says whether the text reaches every workspace', () => {
    const reaching = surface({
      registry: { getSkill: () => skill({ isGlobal: true }) } as never,
    });
    expect(readRevisable(reaching.deps, { kind: 'skill', id: 'skl_1' }, 'description')?.global).toBe(
      true,
    );

    // Attached to one workspace, and `workspaceId` deliberately still set to
    // another: the reach is what decides, and the creator column is not it.
    const confined = surface({
      registry: { getSkill: () => skill({ isGlobal: false, workspaceId: 'ws_other' }) } as never,
    });
    expect(readRevisable(confined.deps, { kind: 'skill', id: 'skl_1' }, 'description')?.global).toBe(
      false,
    );
  });

  it('answers null for a field the target does not have', () => {
    const { deps } = surface();

    expect(readRevisable(deps, { kind: 'workspace', id: 'ws_1' }, 'body')).toBeNull();
  });

  /**
   * Null rather than a throw: a proposal whose target was deleted is one to
   * refuse on the card, not an error to propagate out of a listing.
   */
  it('answers null for a target that has gone', () => {
    const { deps } = surface({
      registry: { getSkill: () => null, upsertSkill: vi.fn(), getAgent: () => null, upsertAgent: vi.fn() } as never,
    });

    expect(readRevisable(deps, { kind: 'skill', id: 'skl_1' }, 'description')).toBeNull();
  });
});

describe('writeRevisable', () => {
  /**
   * The heart of it. `upsertSkill` takes a whole record, so a caller that
   * assembled one from the proposal alone would reset the category, the
   * enabled flag and the workspace — none of which appears on the card. The
   * assertion is on the *call*, because a row is a weaker witness: with the
   * other fields at their defaults, a rebuilt record and a preserved one look
   * identical.
   */
  it('rewrites one field of a skill and passes every other back unchanged', () => {
    const { deps, upsertSkill } = surface();

    writeRevisable(deps, { kind: 'skill', id: 'skl_1' }, 'description', 'Use when a migration ships.');

    expect(upsertSkill).toHaveBeenCalledWith({
      id: 'skl_1',
      workspaceId: 'ws_1',
      name: 'review-migrations',
      description: 'Use when a migration ships.',
      body: '# Review',
      category: 'engineering',
      enabled: false,
    });
  });

  it('rewrites a skill body and leaves the description', () => {
    const { deps, upsertSkill } = surface();

    writeRevisable(deps, { kind: 'skill', id: 'skl_1' }, 'body', '# Review\n\nStep two.');

    expect(upsertSkill.mock.calls[0]?.[0]).toMatchObject({
      description: 'Reviews migrations.',
      body: '# Review\n\nStep two.',
    });
  });

  it('rewrites a subagent prompt and passes its tools and model back unchanged', () => {
    const { deps, upsertAgent } = surface();

    writeRevisable(deps, { kind: 'agent', id: 'agt_1' }, 'prompt', 'Review. Cite the file.');

    expect(upsertAgent).toHaveBeenCalledWith({
      id: 'agt_1',
      workspaceId: 'ws_1',
      name: 'reviewer',
      description: 'Reviews things.',
      prompt: 'Review. Cite the file.',
      category: 'engineering',
      tools: ['Read', 'Grep'],
      model: 'haiku',
      enabled: false,
    });
  });

  it('keeps a subagent’s absent model absent rather than inventing one', () => {
    const { deps, upsertAgent } = surface({
      registry: {
        getSkill: () => null,
        upsertSkill: vi.fn(),
        getAgent: () => agent({ model: null }),
        upsertAgent: vi.fn((input: unknown) => input as never),
      } as never,
    });
    void upsertAgent;

    writeRevisable(deps, { kind: 'agent', id: 'agt_1' }, 'prompt', 'Review.');

    expect((deps.registry.upsertAgent as ReturnType<typeof vi.fn>).mock.calls[0]?.[0]).toMatchObject({
      model: null,
    });
  });

  /**
   * A patch, so the schedule, the description and the failure ceiling stay
   * exactly as they were. A whole-record write here would silently reset the
   * cron expression of an automation whose prompt was improved.
   */
  it('names only the prompt when rewriting an automation', () => {
    const { deps, updateAutomation } = surface();

    writeRevisable(deps, { kind: 'automation', id: 'aut_1' }, 'prompt', 'Review the day, briefly.');

    expect(updateAutomation).toHaveBeenCalledWith('aut_1', { prompt: 'Review the day, briefly.' });
  });

  it('names only the one setting when rewriting a workspace', () => {
    const { deps, updateWorkspace } = surface();

    writeRevisable(deps, { kind: 'workspace', id: 'ws_1' }, 'systemPromptAppend', 'Answer in English.');

    expect(updateWorkspace).toHaveBeenCalledWith('ws_1', {
      settings: { systemPromptAppend: 'Answer in English.' },
    });
  });

  /**
   * The same guard the settings route leans on, on the write rather than on
   * the form — a guard that lived on the form would not be there for this
   * path, and nothing about a proposal coming from a machine lowers the bar.
   */
  it('puts a workspace write through the guard, and refuses what it refuses', () => {
    const guard = vi.fn(() => {
      throw new Error('The system workspace’s safety settings are fixed.');
    });
    const { deps } = surface({ guard });

    expect(() =>
      writeRevisable(deps, { kind: 'workspace', id: 'ws_1' }, 'systemPromptAppend', 'x'),
    ).toThrow(/safety settings/);
    expect(guard).toHaveBeenCalled();
  });

  it('refuses a field the target does not have', () => {
    const { deps } = surface();

    expect(() => writeRevisable(deps, { kind: 'automation', id: 'aut_1' }, 'body', 'x')).toThrow(
      RevisionTargetError,
    );
  });

  it('refuses a target that has gone, for each kind', () => {
    const { deps } = surface({
      workspaces: { get: () => null, update: vi.fn(() => null) } as never,
      registry: { getSkill: () => null, upsertSkill: vi.fn(), getAgent: () => null, upsertAgent: vi.fn() } as never,
      automations: { get: () => null, update: vi.fn(() => null) } as never,
    });

    for (const [kind, field] of [
      ['workspace', 'systemPromptAppend'],
      ['skill', 'description'],
      ['agent', 'prompt'],
      ['automation', 'prompt'],
    ] as const) {
      expect(() => writeRevisable(deps, { kind, id: 'x' }, field, 'y')).toThrow(RevisionTargetError);
    }
  });
});

/**
 * What each field will actually accept, asked of the schema that owns it.
 *
 * A hand-written table of ceilings — 20 000 for a workspace's instructions,
 * 1 024 for a skill's description — would be four copies waiting to drift from
 * their originals. Reading the shape means there is one number and it is the
 * product's own. The failure this prevents is specific: `WorkspaceRepo.update`
 * reparses the whole settings object on write, so a rewrite over the ceiling
 * surfaces as a `ZodError` out of the accept route, a 500 about a proposal
 * that should never have been filed.
 */
describe('fitsField', () => {
  it('has a schema for every field of every target the contract declares', () => {
    for (const kind of RevisionTargetKind.options) {
      for (const field of REVISABLE_FIELDS[kind]) {
        expect(fieldSchema(kind, field)).not.toBeNull();
      }
    }
  });

  it('has none for a field the target does not have', () => {
    expect(fieldSchema('automation', 'description')).toBeNull();
    expect(fieldSchema('workspace', 'body')).toBeNull();
  });

  it('accepts ordinary text for each of them', () => {
    for (const kind of RevisionTargetKind.options) {
      for (const field of REVISABLE_FIELDS[kind]) {
        expect(fitsField(kind, field, 'Use when the thing happens.')).toEqual({ ok: true });
      }
    }
  });

  /**
   * The ceilings differ by two orders of magnitude — a skill's description is
   * 1 024 and its body 200 000 — so one length cannot stand in for the others,
   * and the assertion is that each is enforced by *its own* schema rather than
   * that any particular number is right.
   */
  it('refuses a rewrite longer than the field holds, and says so', () => {
    const enormous = 'x'.repeat(250_000);
    for (const kind of RevisionTargetKind.options) {
      for (const field of REVISABLE_FIELDS[kind]) {
        const answer = fitsField(kind, field, enormous);
        expect(answer.ok).toBe(false);
        if (!answer.ok) expect(answer.reason).toContain(field);
      }
    }
  });

  it('enforces the tight ceiling on a description without touching the loose one on a body', () => {
    const long = 'x'.repeat(2_000);

    expect(fitsField('skill', 'description', long).ok).toBe(false);
    expect(fitsField('skill', 'body', long).ok).toBe(true);
  });

  it('refuses a field the target does not have, rather than pretending', () => {
    expect(fitsField('automation', 'body', 'x')).toMatchObject({ ok: false });
  });
});
