import type { McpTransport, Workspace } from '@metaclaude/shared';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { Db } from '../db/index.js';
import { migrate, openDatabase } from '../db/index.js';
import { defaultWorkspaceSettings, WorkspaceRepo } from '../kernel/repositories.js';
import { Vault } from '../security/vault.js';
import { Registry, RegistryError } from './registry.js';

let db: Db;
let vault: Vault;
let registry: Registry;
let wsA: Workspace;
let wsB: Workspace;

/** Assert that `fn` throws a `RegistryError` carrying `status`. */
function expectRegistryError(fn: () => unknown, status: number, fragment?: string): void {
  try {
    fn();
  } catch (error) {
    expect(error).toBeInstanceOf(RegistryError);
    expect((error as RegistryError).statusCode).toBe(status);
    if (fragment !== undefined) expect((error as Error).message).toContain(fragment);
    return;
  }
  expect.unreachable('expected a RegistryError');
}

beforeEach(() => {
  db = openDatabase({ path: ':memory:' });
  migrate(db);
  vault = new Vault(db, Buffer.alloc(32, 7));
  registry = new Registry(db, vault, () => {
    /* no-op logger */
  });

  const workspaces = new WorkspaceRepo(db);
  wsA = workspaces.create({
    name: 'Alpha',
    slug: 'alpha',
    description: '',
    path: '/tmp/alpha',
    color: '#6366f1',
    icon: 'folder',
    settings: defaultWorkspaceSettings(),
  });
  wsB = workspaces.create({
    name: 'Beta',
    slug: 'beta',
    description: '',
    path: '/tmp/beta',
    color: '#6366f1',
    icon: 'folder',
    settings: defaultWorkspaceSettings(),
  });
});

afterEach(() => {
  db.close();
});

/* -------------------------------------------------------------------------- */
/* Skills                                                                      */
/* -------------------------------------------------------------------------- */

describe('skills', () => {
  it('creates a skill and reads it back', () => {
    const skill = registry.upsertSkill({
      workspaceId: wsA.id,
      name: 'run-tests',
      description: 'How this repository runs its tests',
      body: 'Use `pnpm test`.',
    });

    expect(skill.id.startsWith('skl_')).toBe(true);
    expect(skill.workspaceId).toBe(wsA.id);
    expect(skill.name).toBe('run-tests');
    expect(skill.description).toBe('How this repository runs its tests');
    expect(skill.body).toBe('Use `pnpm test`.');
    expect(skill.enabled).toBe(true);
    expect(skill.autoGenerated).toBe(false);
    expect(skill.useCount).toBe(0);
    expect(registry.getSkill(skill.id)).toEqual(skill);
    expect(registry.getSkill('skl_nope')).toBeNull();
  });

  it('honours the enabled and autoGenerated flags', () => {
    const skill = registry.upsertSkill({
      workspaceId: null,
      name: 'learned',
      description: 'd',
      body: 'b',
      enabled: false,
      autoGenerated: true,
    });
    expect(skill.enabled).toBe(false);
    expect(skill.autoGenerated).toBe(true);
  });

  it('updates in place when an id is supplied', () => {
    const created = registry.upsertSkill({
      workspaceId: wsA.id,
      name: 'run-tests',
      description: 'old',
      body: 'old body',
    });

    const updated = registry.upsertSkill({
      id: created.id,
      workspaceId: wsA.id,
      name: 'run-the-tests',
      description: 'new',
      body: 'new body',
      enabled: false,
    });

    expect(updated.id).toBe(created.id);
    expect(updated.name).toBe('run-the-tests');
    expect(updated.description).toBe('new');
    expect(updated.body).toBe('new body');
    expect(updated.enabled).toBe(false);
    expect(updated.createdAt).toBe(created.createdAt);
    expect(registry.listSkills()).toHaveLength(1);
  });

  it('rejects a bad name', () => {
    for (const name of [
      'Uppercase',
      'has space',
      '-leading-dash',
      '_underscore',
      'trailing.dot',
      'ünïcode',
      '',
      'a'.repeat(65),
    ]) {
      expectRegistryError(
        () => registry.upsertSkill({ workspaceId: null, name, description: 'd', body: 'b' }),
        400,
        'lowercase letters',
      );
    }
    expect(registry.listSkills()).toHaveLength(0);
  });

  it('accepts the names it is documented to accept', () => {
    for (const name of ['a', '9', 'a-b-c', 'skill9', '0-start', 'a'.repeat(64)]) {
      expect(
        registry.upsertSkill({ workspaceId: null, name, description: 'd', body: 'b' }).name,
      ).toBe(name);
    }
  });

  it('rejects a duplicate name in the same scope with 409', () => {
    registry.upsertSkill({ workspaceId: null, name: 'dupe', description: 'd', body: 'b' });
    expectRegistryError(
      () => registry.upsertSkill({ workspaceId: null, name: 'dupe', description: 'd', body: 'b' }),
      409,
      'already exists',
    );

    registry.upsertSkill({ workspaceId: wsA.id, name: 'scoped', description: 'd', body: 'b' });
    expectRegistryError(
      () =>
        registry.upsertSkill({ workspaceId: wsA.id, name: 'scoped', description: 'd', body: 'b' }),
      409,
    );
  });

  it('allows the same name in different scopes', () => {
    registry.upsertSkill({ workspaceId: null, name: 'shared', description: 'g', body: 'b' });
    registry.upsertSkill({ workspaceId: wsA.id, name: 'shared', description: 'a', body: 'b' });
    registry.upsertSkill({ workspaceId: wsB.id, name: 'shared', description: 'b', body: 'b' });
    expect(registry.listSkills()).toHaveLength(3);
  });

  it('throws 404 when updating a skill that is not there', () => {
    expectRegistryError(
      () =>
        registry.upsertSkill({
          id: 'skl_nope',
          workspaceId: null,
          name: 'ghost',
          description: 'd',
          body: 'b',
        }),
      404,
    );
  });

  it('scopes listing: undefined is everything, null is global only, an id adds globals', () => {
    registry.upsertSkill({ workspaceId: null, name: 'global-one', description: 'd', body: 'b' });
    registry.upsertSkill({ workspaceId: wsA.id, name: 'alpha-one', description: 'd', body: 'b' });
    registry.upsertSkill({ workspaceId: wsB.id, name: 'beta-one', description: 'd', body: 'b' });

    expect(registry.listSkills().map((s) => s.name)).toEqual([
      'alpha-one',
      'beta-one',
      'global-one',
    ]);
    expect(registry.listSkills(null).map((s) => s.name)).toEqual(['global-one']);
    expect(registry.listSkills(wsA.id).map((s) => s.name)).toEqual(['alpha-one', 'global-one']);
    expect(registry.listSkills(wsB.id).map((s) => s.name)).toEqual(['beta-one', 'global-one']);
    expect(registry.listSkills('ws_nothing').map((s) => s.name)).toEqual(['global-one']);
  });

  it('deletes', () => {
    const skill = registry.upsertSkill({
      workspaceId: null,
      name: 'temporary',
      description: 'd',
      body: 'b',
    });
    expect(registry.deleteSkill(skill.id)).toBe(true);
    expect(registry.getSkill(skill.id)).toBeNull();
    expect(registry.deleteSkill(skill.id)).toBe(false);
    expect(registry.deleteSkill('skl_nope')).toBe(false);
  });

  // Renaming onto a taken name is as much a conflict as creating a duplicate;
  // it used to escape the update path as a raw driver error and surface as 500.
  it('reports a rename collision as 409, like the insert path does', () => {
    registry.upsertSkill({ workspaceId: null, name: 'taken', description: 'd', body: 'b' });
    const other = registry.upsertSkill({
      workspaceId: null,
      name: 'free',
      description: 'd',
      body: 'b',
    });
    expectRegistryError(
      () =>
        registry.upsertSkill({
          id: other.id,
          workspaceId: null,
          name: 'taken',
          description: 'd',
          body: 'b',
        }),
      409,
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Agents                                                                      */
/* -------------------------------------------------------------------------- */

describe('agents', () => {
  it('creates an agent and reads it back', () => {
    const agent = registry.upsertAgent({
      workspaceId: wsA.id,
      name: 'reviewer',
      description: 'Reviews diffs',
      prompt: 'You review code.',
      tools: ['Read', 'Grep'],
      model: 'sonnet',
    });

    expect(agent.id.startsWith('agt_')).toBe(true);
    expect(agent.workspaceId).toBe(wsA.id);
    expect(agent.name).toBe('reviewer');
    expect(agent.prompt).toBe('You review code.');
    expect(agent.tools).toEqual(['Read', 'Grep']);
    expect(agent.model).toBe('sonnet');
    expect(agent.enabled).toBe(true);
    expect(registry.getAgent(agent.id)).toEqual(agent);
    expect(registry.getAgent('agt_nope')).toBeNull();
  });

  it('round-trips tools as an array, an empty array and null', () => {
    const withTools = registry.upsertAgent({
      workspaceId: null,
      name: 'with-tools',
      description: 'd',
      prompt: 'p',
      tools: ['Bash', 'Write', 'Edit'],
    });
    expect(withTools.tools).toEqual(['Bash', 'Write', 'Edit']);
    expect(registry.getAgent(withTools.id)!.tools).toEqual(['Bash', 'Write', 'Edit']);

    const emptyTools = registry.upsertAgent({
      workspaceId: null,
      name: 'empty-tools',
      description: 'd',
      prompt: 'p',
      tools: [],
    });
    expect(emptyTools.tools).toEqual([]);

    const noTools = registry.upsertAgent({
      workspaceId: null,
      name: 'no-tools',
      description: 'd',
      prompt: 'p',
      tools: null,
    });
    expect(noTools.tools).toBeNull();
    expect(noTools.model).toBeNull();

    const omitted = registry.upsertAgent({
      workspaceId: null,
      name: 'omitted-tools',
      description: 'd',
      prompt: 'p',
    });
    expect(omitted.tools).toBeNull();
  });

  it('updates in place, including clearing the tool list', () => {
    const created = registry.upsertAgent({
      workspaceId: null,
      name: 'reviewer',
      description: 'old',
      prompt: 'old',
      tools: ['Read'],
      model: 'opus',
    });

    const updated = registry.upsertAgent({
      id: created.id,
      workspaceId: null,
      name: 'reviewer',
      description: 'new',
      prompt: 'new',
      tools: null,
      model: null,
      enabled: false,
    });

    expect(updated.id).toBe(created.id);
    expect(updated.description).toBe('new');
    expect(updated.tools).toBeNull();
    expect(updated.model).toBeNull();
    expect(updated.enabled).toBe(false);
    expect(registry.listAgents()).toHaveLength(1);
  });

  it('rejects a bad name', () => {
    for (const name of ['Reviewer', 'my agent', '-lead', 'a'.repeat(65), '']) {
      expectRegistryError(
        () =>
          registry.upsertAgent({ workspaceId: null, name, description: 'd', prompt: 'p' }),
        400,
        'lowercase letters',
      );
    }
  });

  it('rejects a duplicate name in the same scope with 409, but allows it across scopes', () => {
    registry.upsertAgent({ workspaceId: null, name: 'dupe', description: 'd', prompt: 'p' });
    expectRegistryError(
      () => registry.upsertAgent({ workspaceId: null, name: 'dupe', description: 'd', prompt: 'p' }),
      409,
      'already exists',
    );
    expect(
      registry.upsertAgent({ workspaceId: wsA.id, name: 'dupe', description: 'd', prompt: 'p' })
        .name,
    ).toBe('dupe');
  });

  it('throws 404 when updating an agent that is not there', () => {
    expectRegistryError(
      () =>
        registry.upsertAgent({
          id: 'agt_nope',
          workspaceId: null,
          name: 'ghost',
          description: 'd',
          prompt: 'p',
        }),
      404,
    );
  });

  it('scopes listing the same way skills do', () => {
    registry.upsertAgent({ workspaceId: null, name: 'global-agent', description: 'd', prompt: 'p' });
    registry.upsertAgent({ workspaceId: wsA.id, name: 'alpha-agent', description: 'd', prompt: 'p' });
    registry.upsertAgent({ workspaceId: wsB.id, name: 'beta-agent', description: 'd', prompt: 'p' });

    expect(registry.listAgents()).toHaveLength(3);
    expect(registry.listAgents(null).map((a) => a.name)).toEqual(['global-agent']);
    expect(registry.listAgents(wsA.id).map((a) => a.name)).toEqual(['alpha-agent', 'global-agent']);
  });

  it('deletes', () => {
    const agent = registry.upsertAgent({
      workspaceId: null,
      name: 'temporary',
      description: 'd',
      prompt: 'p',
    });
    expect(registry.deleteAgent(agent.id)).toBe(true);
    expect(registry.getAgent(agent.id)).toBeNull();
    expect(registry.deleteAgent(agent.id)).toBe(false);
  });
});

/* -------------------------------------------------------------------------- */
/* MCP servers — validation                                                    */
/* -------------------------------------------------------------------------- */

describe('MCP servers — validation', () => {
  it('requires a command for stdio', () => {
    expectRegistryError(
      () => registry.upsertMcpServer({ workspaceId: null, name: 'local', transport: 'stdio' }),
      400,
      'needs a command',
    );
    expectRegistryError(
      () =>
        registry.upsertMcpServer({
          workspaceId: null,
          name: 'local',
          transport: 'stdio',
          command: '   ',
        }),
      400,
      'needs a command',
    );
    expectRegistryError(
      () =>
        registry.upsertMcpServer({
          workspaceId: null,
          name: 'local',
          transport: 'stdio',
          command: null,
        }),
      400,
    );
    expect(
      registry.upsertMcpServer({
        workspaceId: null,
        name: 'local',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', 'some-server'],
      }).command,
    ).toBe('npx');
  });

  it('requires a URL for sse and http', () => {
    for (const transport of ['sse', 'http'] as McpTransport[]) {
      expectRegistryError(
        () => registry.upsertMcpServer({ workspaceId: null, name: `n-${transport}`, transport }),
        400,
        'needs a URL',
      );
      expectRegistryError(
        () =>
          registry.upsertMcpServer({
            workspaceId: null,
            name: `n-${transport}`,
            transport,
            url: '  ',
          }),
        400,
        'needs a URL',
      );
      expect(
        registry.upsertMcpServer({
          workspaceId: null,
          name: `n-${transport}`,
          transport,
          url: 'https://example.test/mcp',
        }).url,
      ).toBe('https://example.test/mcp');
    }
  });

  it('rejects a URL scheme that is not http or https', () => {
    for (const url of ['ftp://example.test/mcp', 'file:///etc/passwd', 'ws://example.test']) {
      expectRegistryError(
        () => registry.upsertMcpServer({ workspaceId: null, name: 'remote', transport: 'http', url }),
        400,
        'must use http or https',
      );
    }
  });

  it('rejects a malformed URL', () => {
    for (const url of ['not a url', 'http//missing-colon', '://nope']) {
      expectRegistryError(
        () => registry.upsertMcpServer({ workspaceId: null, name: 'remote', transport: 'http', url }),
        400,
        'not valid',
      );
    }
  });

  it('validates the URL even on a stdio server that carries one', () => {
    expectRegistryError(
      () =>
        registry.upsertMcpServer({
          workspaceId: null,
          name: 'local',
          transport: 'stdio',
          command: 'npx',
          url: 'ftp://example.test',
        }),
      400,
      'must use http or https',
    );
  });

  it('rejects a bad server name', () => {
    for (const name of ['has space', 'dot.name', 'slash/name', '', 'a'.repeat(65)]) {
      expectRegistryError(
        () =>
          registry.upsertMcpServer({ workspaceId: null, name, transport: 'stdio', command: 'x' }),
        400,
        'letters, digits, dash and underscore',
      );
    }
    // Upper case, underscores and dashes are all fine here (unlike skills).
    expect(
      registry.upsertMcpServer({
        workspaceId: null,
        name: 'My_Server-1',
        transport: 'stdio',
        command: 'x',
      }).name,
    ).toBe('My_Server-1');
  });

  it('rejects a duplicate name with 409', () => {
    registry.upsertMcpServer({ workspaceId: null, name: 'dupe', transport: 'stdio', command: 'x' });
    expectRegistryError(
      () =>
        registry.upsertMcpServer({
          workspaceId: null,
          name: 'dupe',
          transport: 'stdio',
          command: 'x',
        }),
      409,
      'already exists',
    );
  });
});

/* -------------------------------------------------------------------------- */
/* MCP servers — secret merging                                                */
/* -------------------------------------------------------------------------- */

describe('MCP servers — secret handling', () => {
  function create(env?: Record<string, string>) {
    return registry.upsertMcpServer({
      workspaceId: null,
      name: 'secretive',
      transport: 'stdio',
      command: 'npx',
      args: ['-y', 'server'],
      ...(env ? { env } : {}),
    });
  }

  /** Re-save the server the way an edit form would, with whatever env it shows. */
  function resave(
    id: string,
    patch: { env?: Record<string, string>; removeEnvKeys?: string[]; name?: string } = {},
  ) {
    return registry.upsertMcpServer({
      id,
      workspaceId: null,
      name: patch.name ?? 'secretive',
      transport: 'stdio',
      command: 'npx',
      args: ['-y', 'server'],
      ...(patch.env ? { env: patch.env } : {}),
      ...(patch.removeEnvKeys ? { removeEnvKeys: patch.removeEnvKeys } : {}),
    });
  }

  it('stores the value in the vault and never returns it on the record', () => {
    const server = create({ A: 'secret-a' });

    expect(server.envKeys).toEqual(['A']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('secret-a');
    // The record carries key names only.
    expect(JSON.stringify(server)).not.toContain('secret-a');
    expect(Object.keys(server)).not.toContain('env');
    // …and nothing in the mcp_servers row leaks it either.
    const row = db
      .prepare<[string], Record<string, unknown>>('SELECT * FROM mcp_servers WHERE id = ?')
      .get(server.id)!;
    expect(JSON.stringify(row)).not.toContain('secret-a');
    expect(row.env_keys).toBe('["A"]');
  });

  it('keeps an existing secret when the form submits an empty env map', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { env: {} });

    expect(saved.envKeys).toEqual(['A']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('secret-a');
    // …and the value is still what a run would actually receive.
    const entry = registry.resolve(wsA).mcpServers.secretive as { env: Record<string, string> };
    expect(entry.env).toEqual({ A: 'secret-a' });
  });

  it('keeps an existing secret when the form submits a blank value', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { env: { A: '' } });

    expect(saved.envKeys).toEqual(['A']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('secret-a');
  });

  it('keeps existing secrets when env is omitted entirely', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { name: 'renamed' });

    expect(saved.name).toBe('renamed');
    expect(saved.envKeys).toEqual(['A']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('secret-a');
  });

  it('merges a newly submitted secret alongside the existing ones', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { env: { B: 'secret-b' } });

    expect(saved.envKeys.sort()).toEqual(['A', 'B']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('secret-a');
    expect(vault.get(`mcp:${server.id}`, 'B')).toBe('secret-b');
  });

  it('overwrites a secret when a new non-blank value is submitted for the same key', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { env: { A: 'rotated' } });

    expect(saved.envKeys).toEqual(['A']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBe('rotated');
  });

  it('removes only the keys named in removeEnvKeys', () => {
    const server = create({ A: 'secret-a' });
    resave(server.id, { env: { B: 'secret-b' } });

    const saved = resave(server.id, { removeEnvKeys: ['A'] });

    expect(saved.envKeys).toEqual(['B']);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBeNull();
    expect(vault.get(`mcp:${server.id}`, 'B')).toBe('secret-b');
    expect(vault.listKeys(`mcp:${server.id}`)).toEqual(['B']);
  });

  it('resolves a contradictory save — remove and submit the same key — as a removal', () => {
    const server = create({ A: 'secret-a' });
    const saved = resave(server.id, { env: { A: 'fresh' }, removeEnvKeys: ['A'] });

    // The UI cannot produce this (a removal is derived from keys the draft no
    // longer has), so it only arrives from a caller that asked for both at
    // once. Removal wins: the alternative left the value sealed in the vault
    // under a key that no longer appeared in `env_keys`, which nothing would
    // ever read and only `deleteMcpServer` would ever clean up.
    expect(saved.envKeys).toEqual([]);
    expect(vault.get(`mcp:${server.id}`, 'A')).toBeNull();
    expect(vault.listKeys(`mcp:${server.id}`)).toEqual([]);
  });

  it('clears the whole vault scope when the server is deleted', () => {
    const server = create({ A: 'secret-a' });
    resave(server.id, { env: { B: 'secret-b', C: 'secret-c' } });
    expect(vault.listKeys(`mcp:${server.id}`)).toEqual(['A', 'B', 'C']);

    expect(registry.deleteMcpServer(server.id)).toBe(true);
    expect(vault.listKeys(`mcp:${server.id}`)).toEqual([]);
    expect(registry.getMcpServer(server.id)).toBeNull();
    expect(registry.deleteMcpServer(server.id)).toBe(false);
  });

  it('keeps one server’s secrets away from another’s', () => {
    const first = create({ A: 'secret-a' });
    const second = registry.upsertMcpServer({
      workspaceId: null,
      name: 'other',
      transport: 'stdio',
      command: 'npx',
      env: { A: 'different-a' },
    });

    expect(vault.get(`mcp:${first.id}`, 'A')).toBe('secret-a');
    expect(vault.get(`mcp:${second.id}`, 'A')).toBe('different-a');

    registry.deleteMcpServer(second.id);
    expect(vault.get(`mcp:${first.id}`, 'A')).toBe('secret-a');
  });

  // A phantom update must fail *before* the vault is touched: otherwise the
  // submitted secrets land under `mcp:<unknown id>` with no row to delete them.
  it('throws 404 when updating an MCP server that is not there', () => {
    expectRegistryError(
      () =>
        registry.upsertMcpServer({
          id: 'mcp_nope',
          workspaceId: null,
          name: 'ghost',
          transport: 'stdio',
          command: 'x',
          env: { TOKEN: 'leaked' },
        }),
      404,
    );
    expect(vault.listKeys('mcp:mcp_nope')).toEqual([]);
  });
});

/* -------------------------------------------------------------------------- */
/* MCP servers — header secrets                                                */
/* -------------------------------------------------------------------------- */

describe('MCP servers — header secrets', () => {
  function create(headers?: Record<string, string>) {
    return registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'remote',
      transport: 'http',
      url: 'https://mcp.example.test/v1',
      ...(headers ? { headers } : {}),
    });
  }

  function resave(
    id: string,
    patch: {
      headers?: Record<string, string>;
      removeHeaderKeys?: string[];
      env?: Record<string, string>;
      name?: string;
    } = {},
  ) {
    return registry.upsertMcpServer({
      id,
      workspaceId: wsA.id,
      name: patch.name ?? 'remote',
      transport: 'http',
      url: 'https://mcp.example.test/v1',
      ...(patch.headers ? { headers: patch.headers } : {}),
      ...(patch.removeHeaderKeys ? { removeHeaderKeys: patch.removeHeaderKeys } : {}),
      ...(patch.env ? { env: patch.env } : {}),
    });
  }

  it('seals a header value and never returns it', () => {
    const server = create({ Authorization: 'Bearer super-secret' });

    expect(server.headerKeys).toEqual(['Authorization']);
    expect(JSON.stringify(server)).not.toContain('super-secret');

    // Nor is it anywhere on the row.
    const row = db
      .prepare<[string], Record<string, unknown>>('SELECT * FROM mcp_servers WHERE id = ?')
      .get(server.id)!;
    expect(JSON.stringify(row)).not.toContain('super-secret');
    expect(row.header_keys).toBe('["Authorization"]');
  });

  it('delivers the header to a run', () => {
    create({ Authorization: 'Bearer super-secret', 'X-Tenant': 'acme' });
    const entry = registry.resolve(wsA).mcpServers.remote as { headers: Record<string, string> };
    expect(entry.headers).toEqual({
      Authorization: 'Bearer super-secret',
      'X-Tenant': 'acme',
    });
  });

  it('keeps a stored header when the form submits a blank value', () => {
    const server = create({ Authorization: 'Bearer super-secret' });
    const saved = resave(server.id, { headers: { Authorization: '' }, name: 'renamed' });

    // The form cannot round-trip a value it was never shown, so blank means
    // "leave it alone" — otherwise renaming a server would break its auth.
    expect(saved.name).toBe('renamed');
    expect(saved.headerKeys).toEqual(['Authorization']);
    const entry = registry.resolve(wsA).mcpServers.renamed as { headers: Record<string, string> };
    expect(entry.headers.Authorization).toBe('Bearer super-secret');
  });

  it('rotates, merges and removes headers', () => {
    const server = create({ Authorization: 'Bearer old' });

    const merged = resave(server.id, { headers: { 'X-Tenant': 'acme' } });
    expect(merged.headerKeys.sort()).toEqual(['Authorization', 'X-Tenant']);

    const rotated = resave(server.id, { headers: { Authorization: 'Bearer new' } });
    expect(rotated.headerKeys.sort()).toEqual(['Authorization', 'X-Tenant']);
    const entry = registry.resolve(wsA).mcpServers.remote as { headers: Record<string, string> };
    expect(entry.headers.Authorization).toBe('Bearer new');

    const trimmed = resave(server.id, { removeHeaderKeys: ['Authorization'] });
    expect(trimmed.headerKeys).toEqual(['X-Tenant']);
    expect(vault.get(`mcp:${server.id}`, 'header:Authorization')).toBeNull();
  });

  it('keeps a header and an env var of the same name apart', () => {
    const server = create({ TOKEN: 'header-value' });
    resave(server.id, { env: { TOKEN: 'env-value' } });

    const entry = registry.resolve(wsA).mcpServers.remote as { headers: Record<string, string> };
    // Both are delivered as headers for an HTTP transport, and env wins by
    // being merged last — but they are stored in distinct vault slots.
    expect(vault.get(`mcp:${server.id}`, 'header:TOKEN')).toBe('header-value');
    expect(vault.get(`mcp:${server.id}`, 'TOKEN')).toBe('env-value');
    expect(entry.headers.TOKEN).toBe('env-value');
  });

  it('drops every secret, header slots included, when the server is deleted', () => {
    const server = create({ Authorization: 'Bearer x' });
    resave(server.id, { env: { TOKEN: 'y' } });
    expect(vault.listKeys(`mcp:${server.id}`).sort()).toEqual(['TOKEN', 'header:Authorization']);

    registry.deleteMcpServer(server.id);
    expect(vault.listKeys(`mcp:${server.id}`)).toEqual([]);
  });

  it('drains a legacy plaintext headers column into the vault at construction', () => {
    const server = create();
    // Simulate a row written before headers were sealed.
    db.prepare('UPDATE mcp_servers SET headers = ?, header_keys = ? WHERE id = ?').run(
      JSON.stringify({ Authorization: 'Bearer legacy', 'X-Tenant': 'acme' }),
      '[]',
      server.id,
    );

    const reopened = new Registry(db, vault, () => {
      /* no-op logger */
    });

    const migrated = reopened.getMcpServer(server.id)!;
    expect(migrated.headerKeys.sort()).toEqual(['Authorization', 'X-Tenant']);
    expect(vault.get(`mcp:${server.id}`, 'header:Authorization')).toBe('Bearer legacy');

    const row = db
      .prepare<[string], { headers: string }>('SELECT headers FROM mcp_servers WHERE id = ?')
      .get(server.id)!;
    expect(row.headers).toBe('{}');

    // Idempotent: a second construction finds nothing left to drain.
    const again = new Registry(db, vault, () => {
      /* no-op logger */
    });
    expect(again.getMcpServer(server.id)!.headerKeys.sort()).toEqual(['Authorization', 'X-Tenant']);
  });
});

/* -------------------------------------------------------------------------- */
/* MCP servers — CRUD                                                          */
/* -------------------------------------------------------------------------- */

describe('MCP servers — CRUD', () => {
  it('creates, updates and lists by scope', () => {
    const created = registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'alpha-server',
      transport: 'http',
      url: 'https://example.test/mcp',
      headers: { 'X-Trace': 'on' },
    });

    expect(created.id.startsWith('mcp_')).toBe(true);
    expect(created.transport).toBe('http');
    // Header *names* only — the values are sealed, like the env secrets.
    expect(created.headerKeys).toEqual(['X-Trace']);
    expect(vault.get(`mcp:${created.id}`, 'header:X-Trace')).toBe('on');
    expect(created.args).toEqual([]);
    expect(created.command).toBeNull();
    expect(created.status).toBe('unknown');
    expect(created.lastError).toBeNull();
    expect(created.enabled).toBe(true);

    registry.upsertMcpServer({ workspaceId: null, name: 'global-server', transport: 'stdio', command: 'x' });
    registry.upsertMcpServer({ workspaceId: wsB.id, name: 'beta-server', transport: 'stdio', command: 'x' });

    expect(registry.listMcpServers()).toHaveLength(3);
    expect(registry.listMcpServers(null).map((s) => s.name)).toEqual(['global-server']);
    expect(registry.listMcpServers(wsA.id).map((s) => s.name)).toEqual([
      'alpha-server',
      'global-server',
    ]);
  });

  it('resets the status on every save and lets setMcpStatus record a failure', () => {
    const server = registry.upsertMcpServer({
      workspaceId: null,
      name: 'flappy',
      transport: 'stdio',
      command: 'x',
    });

    registry.setMcpStatus(server.id, 'failed', 'connection refused');
    expect(registry.getMcpServer(server.id)!.status).toBe('failed');
    expect(registry.getMcpServer(server.id)!.lastError).toBe('connection refused');

    const resaved = registry.upsertMcpServer({
      id: server.id,
      workspaceId: null,
      name: 'flappy',
      transport: 'stdio',
      command: 'x',
    });
    expect(resaved.status).toBe('unknown');
    expect(resaved.lastError).toBeNull();

    registry.setMcpStatus(server.id, 'connected');
    expect(registry.getMcpServer(server.id)!.lastError).toBeNull();
  });
});

/* -------------------------------------------------------------------------- */
/* resolve                                                                     */
/* -------------------------------------------------------------------------- */

describe('resolve', () => {
  it('returns an empty context when nothing is registered', () => {
    expect(registry.resolve(wsA)).toEqual({ mcpServers: {}, agents: {} });
  });

  it('builds a stdio entry with the decrypted environment', () => {
    const server = registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'files',
      transport: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-filesystem', '/data'],
      env: { API_KEY: 'sk-test-123', REGION: 'eu' },
    });

    const context = registry.resolve(wsA);
    expect(context.mcpServers).toEqual({
      files: {
        type: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '/data'],
        env: { API_KEY: 'sk-test-123', REGION: 'eu' },
      },
    });
    expect(server.envKeys.sort()).toEqual(['API_KEY', 'REGION']);
  });

  it('merges decrypted secrets over the static headers for an http server', () => {
    registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'remote',
      transport: 'http',
      url: 'https://example.test/mcp',
      headers: { 'X-Trace': 'on', Authorization: 'placeholder' },
      env: { Authorization: 'Bearer real-token' },
    });

    expect(registry.resolve(wsA).mcpServers).toEqual({
      remote: {
        type: 'http',
        url: 'https://example.test/mcp',
        headers: { 'X-Trace': 'on', Authorization: 'Bearer real-token' },
      },
    });
  });

  it('keeps the sse transport tag', () => {
    registry.upsertMcpServer({
      workspaceId: null,
      name: 'events',
      transport: 'sse',
      url: 'https://example.test/sse',
    });
    expect(registry.resolve(wsA).mcpServers).toEqual({
      events: { type: 'sse', url: 'https://example.test/sse', headers: {} },
    });
  });

  it('skips disabled servers and servers belonging to another workspace', () => {
    registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'enabled-server',
      transport: 'stdio',
      command: 'a',
    });
    registry.upsertMcpServer({
      workspaceId: wsA.id,
      name: 'disabled-server',
      transport: 'stdio',
      command: 'b',
      enabled: false,
    });
    registry.upsertMcpServer({
      workspaceId: wsB.id,
      name: 'foreign-server',
      transport: 'stdio',
      command: 'c',
    });
    registry.upsertMcpServer({
      workspaceId: null,
      name: 'global-server',
      transport: 'stdio',
      command: 'd',
    });

    expect(Object.keys(registry.resolve(wsA).mcpServers).sort()).toEqual([
      'enabled-server',
      'global-server',
    ]);
    expect(Object.keys(registry.resolve(wsB).mcpServers).sort()).toEqual([
      'foreign-server',
      'global-server',
    ]);
  });

  it('includes enabled agents keyed by name and skips disabled ones', () => {
    registry.upsertAgent({
      workspaceId: wsA.id,
      name: 'reviewer',
      description: 'Reviews diffs',
      prompt: 'You review code.',
      tools: ['Read', 'Grep'],
      model: 'sonnet',
    });
    registry.upsertAgent({
      workspaceId: wsA.id,
      name: 'minimal',
      description: 'No frills',
      prompt: 'Be brief.',
    });
    registry.upsertAgent({
      workspaceId: wsA.id,
      name: 'switched-off',
      description: 'Off',
      prompt: 'p',
      enabled: false,
    });
    registry.upsertAgent({
      workspaceId: wsB.id,
      name: 'foreign',
      description: 'Elsewhere',
      prompt: 'p',
    });

    const { agents } = registry.resolve(wsA);
    expect(Object.keys(agents).sort()).toEqual(['minimal', 'reviewer']);
    expect(agents.reviewer).toEqual({
      description: 'Reviews diffs',
      prompt: 'You review code.',
      tools: ['Read', 'Grep'],
      model: 'sonnet',
    });
    // Absent optional fields are omitted rather than set to null.
    expect(agents.minimal).toEqual({ description: 'No frills', prompt: 'Be brief.' });
    expect('tools' in (agents.minimal as object)).toBe(false);
    expect('model' in (agents.minimal as object)).toBe(false);
  });

  it('drops a secret the vault can no longer decrypt instead of failing the run', () => {
    const server = registry.upsertMcpServer({
      workspaceId: null,
      name: 'tampered',
      transport: 'stdio',
      command: 'x',
      env: { A: 'secret-a', B: 'secret-b' },
    });
    // Corrupt one ciphertext; GCM authentication will refuse to open it.
    db.prepare("UPDATE secrets SET ciphertext = ? WHERE scope = ? AND key = 'A'").run(
      Buffer.from('garbage'),
      `mcp:${server.id}`,
    );

    const entry = registry.resolve(wsA).mcpServers.tampered as { env: Record<string, string> };
    expect(entry.env).toEqual({ B: 'secret-b' });
  });
});
