/**
 * Extension registry — skills, custom agents and MCP servers.
 *
 * These are what make the OS extensible without redeploying it. All three are
 * stored in the database, scoped either globally or to one workspace, and
 * materialised on demand:
 *
 *  - Agents and MCP servers are passed to the SDK as options.
 *  - Skills are written to disk under the workspace's `.claude/skills/`, which
 *    is where the Claude CLI discovers them.
 */

import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type {
  AgentDefinitionRecord,
  McpServerRecord,
  McpTransport,
  SkillDefinition,
  Workspace,
} from '@metaclaude/shared';
import { newId } from '@metaclaude/shared';
import type { Db } from '../db/index.js';
import { parseJson, toBool, toInt } from '../db/index.js';
import type { RuntimeContext } from '../kernel/kernel.js';
import { isInside } from '../security/paths.js';
import type { Vault } from '../security/vault.js';
import type { PluginRuntime } from './plugin-registry.js';

export class RegistryError extends Error {
  constructor(
    message: string,
    readonly statusCode = 400,
  ) {
    super(message);
    this.name = 'RegistryError';
  }
}

/* -------------------------------------------------------------------------- */
/* Rows                                                                        */
/* -------------------------------------------------------------------------- */

interface SkillRow {
  id: string;
  workspace_id: string | null;
  name: string;
  description: string;
  body: string;
  enabled: number;
  auto_generated: number;
  use_count: number;
  created_at: number;
  updated_at: number;
}

interface AgentRow {
  id: string;
  workspace_id: string | null;
  name: string;
  description: string;
  prompt: string;
  tools: string | null;
  model: string | null;
  enabled: number;
  created_at: number;
  updated_at: number;
}

interface McpRow {
  id: string;
  workspace_id: string | null;
  name: string;
  transport: string;
  command: string | null;
  args: string;
  url: string | null;
  env_keys: string;
  /** Legacy plaintext name→value map, drained into the vault at construction. */
  headers: string;
  header_keys: string;
  enabled: number;
  status: string;
  last_error: string | null;
  created_at: number;
  updated_at: number;
}

const toSkill = (row: SkillRow): SkillDefinition => ({
  id: row.id,
  workspaceId: row.workspace_id,
  name: row.name,
  description: row.description,
  body: row.body,
  enabled: toBool(row.enabled),
  autoGenerated: toBool(row.auto_generated),
  useCount: row.use_count,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

const toAgent = (row: AgentRow): AgentDefinitionRecord => ({
  id: row.id,
  workspaceId: row.workspace_id,
  name: row.name,
  description: row.description,
  prompt: row.prompt,
  tools: row.tools ? parseJson<string[]>(row.tools, []) : null,
  model: row.model,
  enabled: toBool(row.enabled),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

const toMcp = (row: McpRow): McpServerRecord => ({
  id: row.id,
  workspaceId: row.workspace_id,
  name: row.name,
  transport: row.transport as McpTransport,
  command: row.command,
  args: parseJson<string[]>(row.args, []),
  url: row.url,
  envKeys: parseJson<string[]>(row.env_keys, []),
  headerKeys: parseJson<string[]>(row.header_keys, []),
  enabled: toBool(row.enabled),
  status: row.status as McpServerRecord['status'],
  lastError: row.last_error,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

/* -------------------------------------------------------------------------- */
/* Registry                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Run a write that may violate a UNIQUE index, reporting a conflict rather than
 * an internal error.
 *
 * Applied to updates as well as inserts: renaming a record onto a name already
 * taken in the same scope is exactly as much a conflict as creating a duplicate,
 * and letting the raw driver error escape turns a 409 into a 500.
 */
function withConflict<T>(entity: 'A skill' | 'An agent' | 'An MCP server', name: string, fn: () => T): T {
  try {
    return fn();
  } catch (error) {
    if (String(error).includes('UNIQUE')) {
      throw new RegistryError(`${entity} named "${name}" already exists in this scope.`, 409);
    }
    throw error;
  }
}

/**
 * Vault slot for an MCP header value.
 *
 * Headers and env vars share one scope (`mcp:<id>`), so header names are
 * prefixed to keep `Authorization` as a header distinct from a hypothetical
 * `Authorization` env var.
 */
const headerSlot = (name: string): string => `header:${name}`;

/**
 * Merge submitted secret values over the ones already stored.
 *
 * The API never returns a secret value, so an edit form cannot round-trip one:
 * blank submissions mean "keep what is stored", not "clear it". Removal is
 * therefore explicit. Returns the resulting key list plus the writes to apply.
 */
function mergeSecrets(
  existingKeys: readonly string[],
  submittedValues: Record<string, string> | undefined,
  removeKeys: readonly string[] | undefined,
): { keys: string[]; submitted: [string, string][]; removed: string[] } {
  const removed = new Set(removeKeys ?? []);
  const submitted = Object.entries(submittedValues ?? {}).filter(([, value]) => value.length > 0);
  const keys = [...new Set([...existingKeys, ...submitted.map(([key]) => key)])].filter(
    (key) => !removed.has(key),
  );
  return { keys, submitted: submitted.filter(([key]) => !removed.has(key)), removed: [...removed] };
}

export class Registry {
  constructor(
    private readonly db: Db,
    private readonly vault: Vault,
    private readonly log: (level: 'info' | 'warn' | 'error', message: string, data?: unknown) => void,
    /**
     * Installed Agent Plugins, when the deployment has any.
     *
     * Optional so the Registry stays constructible on its own in tests and in
     * any future caller. Plugins are another *source* feeding the two seams
     * this class already owns — `resolve` and `materialiseSkills` — rather than
     * a second mechanism beside them.
     */
    private readonly plugins?: { runtime(): PluginRuntime },
  ) {
    this.drainLegacyHeaders();
  }

  /**
   * Move any header values still stored in plaintext into the vault.
   *
   * Migrations run before the vault exists, so the column could not be drained
   * there. Running it here makes the upgrade lossless: the values are sealed,
   * the names move to `header_keys`, and the plaintext column is emptied. It is
   * a no-op on every boot after the first.
   */
  private drainLegacyHeaders(): void {
    const rows = this.db
      .prepare<[], { id: string; headers: string }>(
        `SELECT id, headers FROM mcp_servers WHERE headers IS NOT NULL AND headers NOT IN ('', '{}')`,
      )
      .all();
    if (rows.length === 0) return;

    const clear = this.db.prepare(
      "UPDATE mcp_servers SET header_keys = ?, headers = '{}' WHERE id = ?",
    );

    for (const row of rows) {
      const legacy = parseJson<Record<string, unknown>>(row.headers, {});
      // A hand-edited or corrupted column must not stop the process booting, so
      // anything that is not a string header value is dropped rather than
      // handed to the sealer.
      const names: string[] = [];
      for (const [name, value] of Object.entries(legacy)) {
        if (typeof value !== 'string' || value.length === 0) continue;
        this.vault.set(`mcp:${row.id}`, headerSlot(name), value);
        names.push(name);
      }
      clear.run(JSON.stringify(names), row.id);
    }
    this.log('info', `sealed MCP headers for ${rows.length} server(s) into the vault`);
  }

  /* ----------------------------- Skills -------------------------------- */

  listSkills(workspaceId?: string | null): SkillDefinition[] {
    const rows =
      workspaceId === undefined
        ? this.db.prepare<[], SkillRow>('SELECT * FROM skills ORDER BY name').all()
        : this.db
            .prepare<[string | null], SkillRow>(
              'SELECT * FROM skills WHERE workspace_id IS ? OR workspace_id IS NULL ORDER BY name',
            )
            .all(workspaceId);
    return rows.map(toSkill);
  }

  getSkill(id: string): SkillDefinition | null {
    const row = this.db.prepare<[string], SkillRow>('SELECT * FROM skills WHERE id = ?').get(id);
    return row ? toSkill(row) : null;
  }

  upsertSkill(input: {
    id?: string;
    workspaceId: string | null;
    name: string;
    description: string;
    body: string;
    enabled?: boolean;
    autoGenerated?: boolean;
  }): SkillDefinition {
    if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(input.name)) {
      throw new RegistryError(
        'A skill name must be lowercase letters, digits and dashes, starting with a letter or digit.',
      );
    }
    const now = Date.now();

    if (input.id) {
      // Reject a phantom update rather than silently doing nothing and
      // returning null typed as a record.
      if (!this.getSkill(input.id)) throw new RegistryError('Skill not found.', 404);

      withConflict('A skill', input.name, () =>
        this.db
          .prepare(
            `UPDATE skills SET name = ?, description = ?, body = ?, enabled = ?, updated_at = ?
             WHERE id = ?`,
          )
          .run(input.name, input.description, input.body, toInt(input.enabled ?? true), now, input.id),
      );
      return this.getSkill(input.id) as SkillDefinition;
    }

    const id = newId('skill');
    withConflict('A skill', input.name, () =>
      this.db
        .prepare(
          `INSERT INTO skills (id, workspace_id, name, description, body, enabled, auto_generated, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .run(
          id,
          input.workspaceId,
          input.name,
          input.description,
          input.body,
          toInt(input.enabled ?? true),
          toInt(input.autoGenerated ?? false),
          now,
          now,
        ),
    );
    return this.getSkill(id) as SkillDefinition;
  }

  deleteSkill(id: string): boolean {
    return this.db.prepare('DELETE FROM skills WHERE id = ?').run(id).changes > 0;
  }

  /**
   * Write the workspace's enabled skills to `.claude/skills/<name>/SKILL.md`,
   * which is where the CLI looks for them.
   *
   * The directory is rebuilt from scratch each time so a deleted or renamed
   * skill cannot linger on disk and keep affecting runs.
   */
  async materialiseSkills(workspace: Workspace): Promise<number> {
    const root = resolve(workspace.path, '.claude', 'skills');
    await rm(root, { recursive: true, force: true });

    const skills = this.listSkills(workspace.id).filter((skill) => skill.enabled);
    const fromPlugins = this.plugins?.runtime().skills ?? [];
    if (skills.length === 0 && fromPlugins.length === 0) return 0;

    await mkdir(root, { recursive: true });

    // Plugins first, so a workspace skill of the same name overwrites one from
    // a plugin. The operator's own definition is the more specific of the two
    // and the only one they can edit.
    //
    // Copied whole rather than rewritten: a plugin skill may ship references
    // and scripts beside its SKILL.md, and writing only the markdown would hand
    // the agent instructions pointing at files that are not there.
    for (const skill of fromPlugins) {
      const from = dirname(skill.path);
      const to = resolve(root, skill.name);
      if (!isInside(root, to)) continue;
      await cp(from, to, { recursive: true, dereference: false }).catch((error: Error) => {
        this.log('warn', `could not materialise skill "${skill.name}" from plugin "${skill.pluginName}"`, {
          message: error.message,
        });
      });
    }

    for (const skill of skills) {
      const directory = resolve(root, skill.name);
      await mkdir(directory, { recursive: true });
      const frontmatter = [
        '---',
        `name: ${skill.name}`,
        `description: ${JSON.stringify(skill.description)}`,
        '---',
        '',
      ].join('\n');
      await writeFile(resolve(directory, 'SKILL.md'), frontmatter + skill.body, 'utf8');
    }
    return skills.length + fromPlugins.length;
  }

  /* ----------------------------- Agents -------------------------------- */

  listAgents(workspaceId?: string | null): AgentDefinitionRecord[] {
    const rows =
      workspaceId === undefined
        ? this.db.prepare<[], AgentRow>('SELECT * FROM agents ORDER BY name').all()
        : this.db
            .prepare<[string | null], AgentRow>(
              'SELECT * FROM agents WHERE workspace_id IS ? OR workspace_id IS NULL ORDER BY name',
            )
            .all(workspaceId);
    return rows.map(toAgent);
  }

  getAgent(id: string): AgentDefinitionRecord | null {
    const row = this.db.prepare<[string], AgentRow>('SELECT * FROM agents WHERE id = ?').get(id);
    return row ? toAgent(row) : null;
  }

  upsertAgent(input: {
    id?: string;
    workspaceId: string | null;
    name: string;
    description: string;
    prompt: string;
    tools?: string[] | null;
    model?: string | null;
    enabled?: boolean;
  }): AgentDefinitionRecord {
    if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(input.name)) {
      throw new RegistryError('An agent name must be lowercase letters, digits and dashes.');
    }
    const now = Date.now();
    const tools = input.tools ? JSON.stringify(input.tools) : null;

    if (input.id) {
      if (!this.getAgent(input.id)) throw new RegistryError('Agent not found.', 404);

      withConflict('An agent', input.name, () =>
        this.db
          .prepare(
            `UPDATE agents SET name = ?, description = ?, prompt = ?, tools = ?, model = ?, enabled = ?, updated_at = ?
             WHERE id = ?`,
          )
          .run(
            input.name,
            input.description,
            input.prompt,
            tools,
            input.model ?? null,
            toInt(input.enabled ?? true),
            now,
            input.id,
          ),
      );
      return this.getAgent(input.id) as AgentDefinitionRecord;
    }

    const id = newId('agent');
    withConflict('An agent', input.name, () =>
      this.db
        .prepare(
          `INSERT INTO agents (id, workspace_id, name, description, prompt, tools, model, enabled, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .run(
          id,
          input.workspaceId,
          input.name,
          input.description,
          input.prompt,
          tools,
          input.model ?? null,
          toInt(input.enabled ?? true),
          now,
          now,
        ),
    );
    return this.getAgent(id) as AgentDefinitionRecord;
  }

  deleteAgent(id: string): boolean {
    return this.db.prepare('DELETE FROM agents WHERE id = ?').run(id).changes > 0;
  }

  /* ------------------------------ MCP ---------------------------------- */

  listMcpServers(workspaceId?: string | null): McpServerRecord[] {
    const rows =
      workspaceId === undefined
        ? this.db.prepare<[], McpRow>('SELECT * FROM mcp_servers ORDER BY name').all()
        : this.db
            .prepare<[string | null], McpRow>(
              'SELECT * FROM mcp_servers WHERE workspace_id IS ? OR workspace_id IS NULL ORDER BY name',
            )
            .all(workspaceId);
    return rows.map(toMcp);
  }

  getMcpServer(id: string): McpServerRecord | null {
    const row = this.db.prepare<[string], McpRow>('SELECT * FROM mcp_servers WHERE id = ?').get(id);
    return row ? toMcp(row) : null;
  }

  /**
   * Create or update an MCP server.
   *
   * Secret values go to the vault; only their key names live on the row, so the
   * configuration stays readable without exposing credentials.
   *
   * Because the API never returns secret values, an edit form cannot round-trip
   * them. Submitted `env` entries are therefore *merged* over what is already
   * stored rather than replacing it — otherwise saving an unrelated field (a
   * renamed server, a toggled `enabled`) would silently destroy every
   * credential. Removing a secret is an explicit act: name it in `removeEnvKeys`.
   */
  upsertMcpServer(input: {
    id?: string;
    workspaceId: string | null;
    name: string;
    transport: McpTransport;
    command?: string | null;
    args?: string[];
    url?: string | null;
    env?: Record<string, string>;
    /** Secret keys to delete outright. */
    removeEnvKeys?: string[];
    /** Header values, merged and sealed on exactly the same terms as `env`. */
    headers?: Record<string, string>;
    /** Header names to delete outright. */
    removeHeaderKeys?: string[];
    enabled?: boolean;
  }): McpServerRecord {
    if (!/^[a-zA-Z0-9_-]{1,64}$/.test(input.name)) {
      throw new RegistryError('An MCP server name may contain letters, digits, dash and underscore.');
    }
    if (input.transport === 'stdio' && !input.command?.trim()) {
      throw new RegistryError('A stdio MCP server needs a command.');
    }
    if (input.transport !== 'stdio' && !input.url?.trim()) {
      throw new RegistryError(`A ${input.transport} MCP server needs a URL.`);
    }
    if (input.url) {
      let parsed: URL;
      try {
        parsed = new URL(input.url);
      } catch {
        throw new RegistryError('The MCP server URL is not valid.');
      }
      if (!['http:', 'https:'].includes(parsed.protocol)) {
        throw new RegistryError('The MCP server URL must use http or https.');
      }
    }

    const now = Date.now();
    const id = input.id ?? newId('mcpServer');

    // Resolve the target row *before* touching the vault. An update naming a
    // server that does not exist has to fail here: further down, the UPDATE
    // would match zero rows while the submitted secrets were still written
    // under `mcp:<unknown id>`, leaving orphan credentials that no delete path
    // can ever reach.
    const existing = input.id ? this.getMcpServer(input.id) : null;
    if (input.id && !existing) throw new RegistryError('MCP server not found.', 404);

    // Merge the submitted secret keys over the existing ones, minus any the
    // caller explicitly asked to remove. Blank values are ignored so a form
    // that shows empty secret fields (as it must) keeps what is stored.
    const env = mergeSecrets(existing?.envKeys ?? [], input.env, input.removeEnvKeys);
    const headers = mergeSecrets(existing?.headerKeys ?? [], input.headers, input.removeHeaderKeys);

    // The row is written first, so a rejected write (a rename onto a name
    // already taken) leaves the stored credentials exactly as they were.
    if (input.id) {
      withConflict('An MCP server', input.name, () =>
        this.db
          .prepare(
            `UPDATE mcp_servers SET
               name = ?, transport = ?, command = ?, args = ?, url = ?,
               env_keys = ?, header_keys = ?, headers = '{}',
               enabled = ?, status = 'unknown', last_error = NULL, updated_at = ?
             WHERE id = ?`,
          )
          .run(
            input.name,
            input.transport,
            input.command ?? null,
            JSON.stringify(input.args ?? []),
            input.url ?? null,
            JSON.stringify(env.keys),
            JSON.stringify(headers.keys),
            toInt(input.enabled ?? true),
            now,
            input.id,
          ),
      );
    } else {
      withConflict('An MCP server', input.name, () =>
        this.db
          .prepare(
            `INSERT INTO mcp_servers
               (id, workspace_id, name, transport, command, args, url, env_keys, header_keys,
                enabled, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          )
          .run(
            id,
            input.workspaceId,
            input.name,
            input.transport,
            input.command ?? null,
            JSON.stringify(input.args ?? []),
            input.url ?? null,
            JSON.stringify(env.keys),
            JSON.stringify(headers.keys),
            toInt(input.enabled ?? true),
            now,
            now,
          ),
      );
    }

    for (const key of env.removed) this.vault.delete(`mcp:${id}`, key);
    for (const [key, value] of env.submitted) this.vault.set(`mcp:${id}`, key, value);

    for (const key of headers.removed) this.vault.delete(`mcp:${id}`, headerSlot(key));
    for (const [key, value] of headers.submitted) {
      this.vault.set(`mcp:${id}`, headerSlot(key), value);
    }

    return this.getMcpServer(id) as McpServerRecord;
  }

  deleteMcpServer(id: string): boolean {
    this.vault.deleteScope(`mcp:${id}`);
    return this.db.prepare('DELETE FROM mcp_servers WHERE id = ?').run(id).changes > 0;
  }

  setMcpStatus(id: string, status: McpServerRecord['status'], error?: string | null): void {
    this.db
      .prepare('UPDATE mcp_servers SET status = ?, last_error = ?, updated_at = ? WHERE id = ?')
      .run(status, error ?? null, Date.now(), id);
  }

  /* --------------------------- Materialisation -------------------------- */

  /**
   * Build the runtime context handed to the supervisor for a workspace.
   * Called once per run, so it must stay cheap: it is a handful of indexed
   * reads plus vault decryption for the enabled servers only.
   */
  resolve(workspace: Workspace): RuntimeContext {
    const mcpServers: Record<string, unknown> = {};

    for (const server of this.listMcpServers(workspace.id)) {
      if (!server.enabled) continue;

      try {
        if (server.transport === 'stdio') {
          if (!server.command) continue;
          mcpServers[server.name] = {
            type: 'stdio',
            command: server.command,
            args: server.args,
            env: this.vault.resolveEnv(`mcp:${server.id}`, server.envKeys),
          };
        } else {
          if (!server.url) continue;
          // Env secrets are still merged in for an HTTP server: it has no
          // subprocess environment, so the env field is the natural place an
          // operator puts a token, and dropping it here would silently break
          // servers configured that way.
          const sealedHeaders = this.vault.resolveEnv(
            `mcp:${server.id}`,
            server.headerKeys.map(headerSlot),
          );
          mcpServers[server.name] = {
            type: server.transport,
            url: server.url,
            headers: {
              ...Object.fromEntries(
                server.headerKeys.map((name) => [name, sealedHeaders[headerSlot(name)] ?? '']),
              ),
              ...this.vault.resolveEnv(`mcp:${server.id}`, server.envKeys),
            },
          };
        }
      } catch (error) {
        // One misconfigured server must not prevent the run from starting.
        this.log('warn', `skipping MCP server "${server.name}"`, {
          message: (error as Error).message,
        });
        this.setMcpStatus(server.id, 'failed', (error as Error).message);
      }
    }

    // Plugin servers are added after the workspace's own and are namespaced,
    // so a plugin cannot shadow a server the operator configured themselves.
    for (const [name, server] of Object.entries(this.plugins?.runtime().mcpServers ?? {})) {
      mcpServers[name] = server;
    }

    const agents: RuntimeContext['agents'] = {};
    for (const agent of this.listAgents(workspace.id)) {
      if (!agent.enabled) continue;
      agents[agent.name] = {
        description: agent.description,
        prompt: agent.prompt,
        ...(agent.tools ? { tools: agent.tools } : {}),
        ...(agent.model ? { model: agent.model } : {}),
      };
    }

    return { mcpServers, agents };
  }
}
